In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import dabl

In [3]:
df = pd.read_csv('../../data/raw/Zillow_month.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27317 entries, 0 to 27316
Columns: 276 entries, RegionID to 2022-03-31
dtypes: float64(267), int64(3), object(6)
memory usage: 57.5+ MB

In [4]:
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,322791.0,...,1098893.0,1107554.0,1116367.0,1126666.0,1131034.0,1130418.0,1130985.0,1136847.0,1148541.0,1167157.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,312893.0,...,512225.0,516042.0,520532.0,523117.0,525702.0,528495.0,530491.0,531877.0,532090.0,534766.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,503959.0,...,1458014.0,1459861.0,1474220.0,1489954.0,1498567.0,1502806.0,1503119.0,1513679.0,1523377.0,1540289.0
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,224754.0,...,390371.0,401127.0,412023.0,421155.0,429123.0,436214.0,441955.0,448057.0,457598.0,469289.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,405296.0,...,650071.0,653814.0,658818.0,661985.0,665873.0,670492.0,673398.0,675298.0,675062.0,678138.0

In [63]:
cali = df[df['StateName']=='CA'].copy()
cali.rename(columns={'RegionName':'Zipcode'},inplace=True)
cali.drop(['RegionType','RegionID','Metro','StateName','State'],axis=1,inplace=True)
cali.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1575 entries, 13 to 27312
Columns: 271 entries, SizeRank to 2022-03-31
dtypes: float64(267), int64(2), object(2)
memory usage: 3.3+ MB

In [64]:
info = cali.columns[:10]
cali[info].head()

,SizeRank,Zipcode,City,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30
13,13,94109,San Francisco,San Francisco County,505724.0,508437.0,512673.0,521329.0,531340.0,542300.0
21,22,90250,Hawthorne,Los Angeles County,208066.0,208356.0,209254.0,211117.0,213623.0,215917.0
39,40,94565,Pittsburg,Contra Costa County,272514.0,273306.0,273888.0,275090.0,277059.0,279179.0
43,44,90046,Los Angeles,Los Angeles County,463117.0,463879.0,467076.0,471449.0,476230.0,479488.0
87,88,94501,Alameda,Alameda County,335259.0,337169.0,339974.0,350554.0,364470.0,374762.0

In [60]:
cali.iloc[:,:]

,SizeRank,Zipcode,StateName,State,City,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,...,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31
13,13,94109,CA,CA,San Francisco,San Francisco County,505724.0,508437.0,512673.0,521329.0,...,1169002.0,1186659.0,1198646.0,1209774.0,1216285.0,1218451.0,1220499.0,1218921.0,1230029.0,1243797.0
21,22,90250,CA,CA,Hawthorne,Los Angeles County,208066.0,208356.0,209254.0,211117.0,...,801938.0,822215.0,834074.0,839174.0,838377.0,839489.0,842610.0,846070.0,853240.0,867265.0
39,40,94565,CA,CA,Pittsburg,Contra Costa County,272514.0,273306.0,273888.0,275090.0,...,705928.0,734211.0,748843.0,762141.0,763295.0,771004.0,779030.0,791446.0,798828.0,809441.0
43,44,90046,CA,CA,Los Angeles,Los Angeles County,463117.0,463879.0,467076.0,471449.0,...,1631080.0,1653887.0,1672941.0,1686261.0,1684730.0,1680882.0,1684123.0,1685433.0,1694694.0,1719604.0
87,88,94501,CA,CA,Alameda,Alameda County,335259.0,337169.0,339974.0,350554.0,...,1280110.0,1325533.0,1355802.0,1366180.0,1354329.0,1348411.0,1354794.0,1374253.0,1399648.0,1424869.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27282,33114,95715,CA,CA,Soda Springs,Placer County,NaN,NaN,NaN,NaN,...,311789.0,323697.0,336963.0,344213.0,345645.0,345863.0,351978.0,356976.0,363682.0,361191.0
27289,33451,95981,CA,CA,Strawberry Valley,Plumas County,NaN,NaN,NaN,NaN,...,278415.0,282353.0,285600.0,290576.0,294004.0,297599.0,302152.0,305259.0,308453.0,309599.0
27290,33487,95724,CA,CA,Soda Springs,Placer County,267437.0,266982.0,269428.0,272993.0,...,863184.0,915474.0,970401.0,1007626.0,1021796.0,1030757.0,1040779.0,1056410.0,1064143.0,1065049.0
27308,34322,95375,CA,CA,Strawberry,Tuolumne County,NaN,NaN,NaN,NaN,...,360785.0,378806.0,392589.0,402934.0,403109.0,397683.0,395974.0,396834.0,407741.0,416287.0
27312,34430,95721,CA,CA,Twin Bridges,El Dorado County,282898.0,282348.0,283598.0,285427.0,...,375551.0,389851.0,407400.0,423445.0,433012.0,434372.0,434282.0,443324.0,444062.0,444731.0

In [70]:
# calc average price 

cali['2021_avg_price']= (cali['2021-01-31']+ cali['2021-02-28']+
cali['2021-02-28']+cali['2021-03-31']+cali['2021-04-30']+ cali['2021-05-31']+cali['2021-06-30']
+ cali['2021-07-31']+cali['2021-08-31']+cali['2021-09-30']+cali['2021-10-31'] +cali['2021-11-30']
+cali['2021-12-31'])/12

In [71]:
cali[['SizeRank', 'Zipcode', 'City', 
       'CountyName','2021_avg_price','2021-01-31','2021-12-31','2022-01-31']][:-5]

,SizeRank,Zipcode,City,CountyName,2021_avg_price,2021-01-31,2021-12-31,2022-01-31
13,13,94109,San Francisco,San Francisco County,1.280458e+06,1162490.0,1220499.0,1218921.0
21,22,90250,Hawthorne,Los Angeles County,8.639297e+05,741584.0,842610.0,846070.0
39,40,94565,Pittsburg,Contra Costa County,7.682227e+05,645426.0,779030.0,791446.0
43,44,90046,Los Angeles,Los Angeles County,1.771814e+06,1576910.0,1684123.0,1685433.0
87,88,94501,Alameda,Alameda County,1.376276e+06,1153671.0,1354794.0,1374253.0
...,...,...,...,...,...,...,...,...
27208,32209,95646,Kirkwood,Alpine County,6.312485e+05,534329.0,633373.0,643919.0
27216,32244,93605,Big Creek,Fresno County,5.314276e+05,437865.0,539707.0,549472.0
27235,32447,96108,New Pine Creek,Modoc County,2.014294e+05,174253.0,199380.0,202394.0
27237,32447,96115,Lake City,Modoc County,2.512786e+05,213084.0,251179.0,254172.0
27275,32844,93554,Randsburg,Kern County,NaN,NaN,NaN,NaN

In [73]:
## check nulls 
m = pd.DataFrame([cali.isnull().sum(),100*cali.isnull().mean()])
m = m.T
m.columns=['count', '%']
m = m.sort_values(by='count',ascending=False)
m.head(15)

            count          %
2000-01-31  383.0  24.317460
2000-02-29  380.0  24.126984
2000-03-31  380.0  24.126984
2000-11-30  379.0  24.063492
2000-06-30  379.0  24.063492
2000-12-31  379.0  24.063492
2000-10-31  379.0  24.063492
2000-09-30  379.0  24.063492
2000-07-31  379.0  24.063492
2000-08-31  379.0  24.063492
2000-05-31  379.0  24.063492
2000-04-30  379.0  24.063492
2001-01-31  340.0  21.587302
2004-03-31  329.0  20.888889
2003-12-31  327.0  20.761905

In [74]:
cali['2021_avg_price'].isnull().sum()

38

In [76]:
cali[cali['2021_avg_price'].isnull()]

,SizeRank,Zipcode,City,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,...,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2021_avg_price
563,566,92122,San Diego,San Diego County,272388.0,273646.0,275400.0,279056.0,282861.0,287427.0,...,949280.0,967755.0,980580.0,989397.0,1001625.0,1017961.0,1045133.0,1074242.0,1110402.0,NaN
1486,1498,93033,Oxnard,Ventura County,206655.0,207754.0,208806.0,210821.0,212621.0,214733.0,...,585852.0,597855.0,606173.0,610765.0,615530.0,621445.0,630010.0,642685.0,654645.0,NaN
1690,1703,92127,San Diego,San Diego County,359397.0,361382.0,363269.0,367787.0,372160.0,378609.0,...,1266568.0,1297089.0,1323676.0,1341328.0,1365947.0,1395290.0,1440473.0,1484945.0,1534513.0,NaN
2838,2862,93036,Oxnard,Ventura County,222623.0,223692.0,224919.0,227130.0,229357.0,231690.0,...,670554.0,684656.0,693726.0,698042.0,701418.0,706786.0,717113.0,732918.0,749220.0,NaN
4205,4248,93004,Ventura,Ventura County,270826.0,271520.0,272572.0,274579.0,276822.0,279001.0,...,740599.0,754283.0,763024.0,765454.0,768485.0,773268.0,784545.0,800084.0,817410.0,NaN
5544,5598,95531,Crescent City,Del Norte County,NaN,NaN,NaN,NaN,NaN,NaN,...,298288.0,303197.0,308859.0,312523.0,315596.0,319329.0,325290.0,331304.0,335132.0,NaN
9452,9569,96067,Mount Shasta,Siskiyou County,NaN,NaN,NaN,NaN,NaN,NaN,...,377657.0,385361.0,392596.0,397432.0,400969.0,406560.0,412298.0,417610.0,420901.0,NaN
10899,11041,96094,Weed,Siskiyou County,NaN,NaN,NaN,NaN,NaN,NaN,...,269474.0,274956.0,280034.0,283765.0,286904.0,291604.0,296103.0,300096.0,302701.0,NaN
13342,13545,95987,Williams,Colusa County,NaN,NaN,NaN,NaN,NaN,NaN,...,291987.0,297360.0,303190.0,307695.0,311943.0,316974.0,321873.0,326945.0,330392.0,NaN
16386,16773,96025,Dunsmuir,Siskiyou County,NaN,NaN,NaN,NaN,NaN,NaN,...,210821.0,215406.0,220351.0,223471.0,225785.0,228989.0,232811.0,236127.0,238284.0,NaN
16902,17333,95567,Smith River,Del Norte County,NaN,NaN,NaN,NaN,NaN,NaN,...,403278.0,409547.0,415894.0,420519.0,423522.0,427731.0,434702.0,441280.0,446622.0,NaN
22835,24441,93526,Independence,Inyo County,NaN,NaN,NaN,NaN,NaN,NaN,...,245556.0,249730.0,254139.0,257871.0,261123.0,265667.0,269909.0,274092.0,276115.0,NaN
23028,24682,95565,Scotia,Humboldt County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,288603.0,293813.0,297853.0,308030.0,318559.0,327516.0,331285.0,NaN
23178,24888,96120,Kirkwood,Alpine County,NaN,NaN,NaN,NaN,NaN,NaN,...,464260.0,472732.0,480313.0,484898.0,489523.0,496536.0,503933.0,510619.0,514379.0,NaN
23288,25025,96058,Macdoel,Siskiyou County,NaN,NaN,NaN,NaN,NaN,NaN,...,89679.0,91513.0,93027.0,93956.0,94713.0,96072.0,97645.0,98766.0,99293.0,NaN
23316,25071,95943,Glenn,Glenn County,NaN,NaN,NaN,NaN,NaN,NaN,...,675982.0,686048.0,709859.0,726143.0,747823.0,759333.0,772552.0,782434.0,792587.0,NaN
23360,25120,95251,Vallecito,Calaveras County,NaN,NaN,NaN,NaN,NaN,NaN,...,327703.0,NaN,361778.0,369047.0,368506.0,363722.0,364705.0,363466.0,366168.0,NaN
23515,25315,91210,Glendale,Los Angeles County,NaN,NaN,NaN,NaN,NaN,NaN,...,1004098.0,1014456.0,1019827.0,1022840.0,1033449.0,1046348.0,1059449.0,1073762.0,1093302.0,NaN
23717,25574,96106,Clio,Plumas County,NaN,NaN,NaN,NaN,NaN,NaN,...,541110.0,550549.0,560783.0,568312.0,575426.0,583725.0,593102.0,601043.0,605883.0,NaN
23800,25688,95317,El Nido,Merced County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,698684.0,723667.0,742712.0,765557.0,769305.0,770736.0,769002.0,NaN
25099,27582,95554,Myers Flat,Humboldt County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,411964.0,411894.0,417568.0,426088.0,432847.0,440906.0,NaN
25165,27695,95558,Ferndale,Humboldt County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,634609.0,651071.0,678658.0,682573.0,674233.0,651454.0,NaN
25363,28012,96090,Tehama,Tehama County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,204736.0,202806.0,204016.0,205178.0,206886.0,209746.0,NaN
25769,28677,95913,Willows,Glenn County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,337515.0,341536.0,346589.0,350834.0,354082.0,356581.0,NaN
26174,29401,95639,Clarksburg,Yolo County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,422440.0,NaN
26210,29472,93549,Olancha,Inyo County,NaN,NaN,NaN,NaN,NaN,NaN,...,179858.0,180890.0,182384.0,182448.0,184521.0,187522.0,192524.0,195293.0,196151.0,NaN
26297,29653,95717,Gold Run,Placer County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,433349.0,433073.0,435938.0,440400.0,448152.0,NaN
26342,29726,95511,Alderpoint,Humboldt County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297797.0,303667.0,NaN
26361,29762,93226,Glennville,Kern County,NaN,NaN,NaN,NaN,NaN,NaN,...,237984.0,246564.0,255659.0,260346.0,265182.0,268032.0,269832.0,271657.0,275295.0,NaN
26560,30222,95920,Butte City,Glenn County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,508737.0,516439.0,524879.0,534299.0,540211.0,545390.0,NaN
26601,30304,95607,Capay,Yolo County,NaN,NaN,NaN,NaN,NaN,NaN,...,1063325.0,1088177.0,1075514.0,1018102.0,975999.0,952667.0,938283.0,923055.0,907708.0,NaN
26858,30939,91948,Mount Laguna,San Diego County,NaN,NaN,NaN,NaN,NaN,NaN,...,263151.0,276256.0,289409.0,299290.0,308773.0,312333.0,312180.0,304677.0,305089.0,NaN
26894,31043,96112,Fort Bidwell,Modoc County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135406.0,NaN
26913,31077,93954,San Lucas,Monterey County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,399104.0,402641.0,398129.0,406978.0,413150.0,427427.0,438591.0,NaN
26922,31114,94940,Marshall,Marin County,NaN,NaN,NaN,NaN,NaN,NaN,...,1370600.0,1414872.0,1427982.0,1414141.0,1407938.0,1394390.0,1373517.0,1368308.0,1398733.0,NaN
27021,31457,95493,Upper Lake,Lake County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,511631.0,516663.0,513047.0,513418.0,NaN
27084,31646,93528,Johannesburg,Kern County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109992.0,107698.0,NaN
27275,32844,93554,Randsburg,Kern County,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106950.0,NaN

In [99]:
county_avg=cali.groupby('CountyName')['2022-03-31', '2021_avg_price'].mean()
county_avg.shape

<ipython-input-99-8567b6d6e019>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  county_avg=cali.groupby('CountyName')['2022-03-31', '2021_avg_price'].mean()

(58, 2)

In [100]:
city_avg['2021_avg_price'][:4]

City
Acampo      797258.166667
Acton       823586.583333
Adelanto    329858.166667
Adin        162127.916667
Name: 2021_avg_price, dtype: float64

In [101]:
cali['2021_avg_price'].fillna(cali.groupby('City')['2021_avg_price'].mean())

13       1.280458e+06
21       8.639297e+05
39       7.682227e+05
43       1.771814e+06
87       1.376276e+06
             ...
27282    3.500590e+05
27289    3.027878e+05
27290    9.536639e+05
27308    3.988684e+05
27312    4.127067e+05
Name: 2021_avg_price, Length: 1575, dtype: float64

In [102]:
cali['2021_avg_price'].isnull().sum()

38

In [97]:
city_avg=cali.groupby('City')['2022-03-31', '2021_avg_price'].mean()
city_avg

<ipython-input-97-927e231267bc>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  city_avg=cali.groupby('City')['2022-03-31', '2021_avg_price'].mean()

              2022-03-31  2021_avg_price
City
Acampo          823920.0    7.972582e+05
Acton           865322.0    8.235866e+05
Adelanto        365540.0    3.298582e+05
Adin            165110.0    1.621279e+05
Agoura Hills   1218009.0    1.150227e+06
...                  ...             ...
Yountville     1339008.0    1.313412e+06
Yreka           248877.0    2.383657e+05
Yuba City       441002.0    4.264734e+05
Yucaipa         545576.0    5.145279e+05
Yucca Valley    440103.5    3.901014e+05

[935 rows x 2 columns]

In [90]:
cali[cali['Zipcode']==94940][['2021-01-31',
       '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31',
       '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30',
       '2021-10-31', '2021-11-30', '2021-12-31']]

,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31
26922,NaN,NaN,NaN,1256633.0,1284231.0,1309156.0,1370600.0,1414872.0,1427982.0,1414141.0,1407938.0,1394390.0